### PR TITLE
Add a scheduler to do nightly imports automatically

### PR DESCRIPTION
**Pull request by pnegahdar**
Also no problem! Thanks for open sourcing this :)

### CODE REVIEW

**Comment by pnegahdar** [comment]
Is nightly the right default rate for this?

**Comment by johnb30** [comment]
The default we usually go with is hourly. See https://github.com/openeventdata/eldiablo/blob/master/crontab.txt#L1 for an example.

**Comment by pnegahdar** [comment]
Updated for hourly

**Comment by johnb30** [comment]
:+1:

**Pull request merged**
